// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: passwords.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const setEmail = `-- name: SetEmail :exec
UPDATE users
SET email = $1
WHERE id = $2
`

type SetEmailParams struct {
	Email string
	ID    uuid.UUID
}

func (q *Queries) SetEmail(ctx context.Context, arg SetEmailParams) error {
	_, err := q.db.ExecContext(ctx, setEmail, arg.Email, arg.ID)
	return err
}

const setPassword = `-- name: SetPassword :exec
UPDATE users
SET hashed_password = $1
WHERE id = $2
`

type SetPasswordParams struct {
	HashedPassword string
	ID             uuid.UUID
}

func (q *Queries) SetPassword(ctx context.Context, arg SetPasswordParams) error {
	_, err := q.db.ExecContext(ctx, setPassword, arg.HashedPassword, arg.ID)
	return err
}
